<h1>TASK 4.2</h1>

Question 1

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import os
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:

X_train_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/X_train_tsfel.csv')
y_train_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/y_train_tsfel.csv')
X_test_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/X_collected_tsfel.csv')
y_test_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/y_collected_tsfel.csv')

In [9]:
X_test_tsfel

0_Absolute energy  0_Area under the curve  0_Autocorrelation  \
0           2465.7580                 6.55735                2.0   
1           1678.5701                 5.86805                2.0   
2           1282.8568                 5.13520                2.0   
3           1215.6256                 4.76845                2.0   
4           1360.8524                 5.10645                2.0   
5           1028.5090                 4.76640                2.0   
6           1217.7520                 5.07855                2.0   
7            955.3248                 4.66765                2.0   
8              0.8004                 0.12330                2.0   
9              0.4046                 0.10400                3.0   
10             0.3718                 0.09250                3.0   
11             0.3066                 0.08820                3.0   
12             0.3201                 0.08095                2.0   
13             0.4639                 0.10415                2.0   
14             0.9234                 0.11110                2.0   
15           321.6736                 1.17390               18.0   
16             1.0144                 0.15455                2.0   
17             1.4665                 0.19070                2.0   
18            16.5260                 0.42705                2.0   
19            12.0971                 0.41310                2.0   
20           988.8076                 4.84040                2.0   
21           993.5936                 4.80390                2.0   
22          1255.8310                 5.40500                2.0   
23          1095.2519                 5.11725                2.0   

    0_Average power  0_Centroid  0_ECDF Percentile Count_0  \
0        494.139880    3.153675                      100.0   
1        336.386794    2.675909                      100.0   
2        257.085531    3.112982                      100.0   
3        243.612345    2.429101                      100.0   
4        272.715912    2.412520                      100.0   
5        206.114028    2.658732                      100.0   
6        244.038477    2.356328                      100.0   
7        191.447856    2.306377                      100.0   
8          0.160401    1.418743                      100.0   
9          0.081082    1.729580                      100.0   
10         0.074509    1.454513                      100.0   
11         0.061443    1.814827                      100.0   
12         0.064148    2.659947                      100.0   
13         0.092966    2.039763                      100.0   
14         0.185050    2.564174                      100.0   
15        64.463647    4.720683                      100.0   
16         0.203287    2.737726                      100.0   
17         0.293888    2.013817                      100.0   
18         3.311824    1.971743                      100.0   
19         2.424269    1.899951                      100.0   
20       198.157836    2.642939                      100.0   
21       199.116954    2.287434                      100.0   
22       251.669539    2.301603                      100.0   
23       219.489359    2.474651                      100.0   

    0_ECDF Percentile Count_1  0_ECDF Percentile_0  0_ECDF Percentile_1  \
0                       400.0                -1.12                 1.34   
1                       400.0                -1.10                 1.18   
2                       400.0                -1.04                 1.08   
3                       400.0                -0.80                 0.94   
4                       400.0                -0.66                 1.22   
5                       400.0                -0.59                 1.28   
6                       400.0                -0.70                 1.27   
7                       400.0                -0.67                 1.19   
8                       400.0                -0.02                 0.03   
9 

In [8]:
y_test_tsfel

3.000000000000000000e+00
0                        3.0
1                        3.0
2                        3.0
3                        2.0
4                        2.0
5                        2.0
6                        2.0
7                        6.0
8                        6.0
9                        6.0
10                       6.0
11                       4.0
12                       4.0
13                       4.0
14                       4.0
15                       5.0
16                       5.0
17                       5.0
18                       5.0
19                       1.0
20                       1.0
21                       1.0
22                       1.0

In [3]:
df = pd.DataFrame()
df_test = pd.DataFrame()
dict1 = {"LAYING":0,
"SITTING":1,
"STANDING":2,
"WALKING":3,
"WALKING_DOWNSTAIRS":4,
"WALKING_UPSTAIRS":5}

In [79]:

base_path = "/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/Combined/Train"

# Initialize an empty DataFrame
df = pd.DataFrame()

for files in os.listdir(base_path):
    full_path = os.path.join(base_path, files)
    if os.path.isdir(full_path):  # Ensure `files` is a directory
        for dfs in os.listdir(full_path):
            dfs_full_path = os.path.join(full_path, dfs)
            if os.path.isfile(dfs_full_path):  # Ensure `dfs` is a file
                df1 = pd.read_csv(dfs_full_path)
                df1["Label"] = np.array([dict1[files]] * df1.shape[0])
                df = pd.concat([df, df1], axis=0)

# Now `df` contains the combined DataFrame

In [15]:
X_train_tsfel

0_Absolute energy  0_Area under the curve  0_Autocorrelation  \
0           428.119592                4.504459                5.0   
1            32.768542                1.276929               26.0   
2           478.627177                4.882182                5.0   
3           477.002571                4.747669                5.0   
4           530.466450                5.002581                6.0   
..                 ...                     ...                ...   
121         497.739114                4.877595                3.0   
122         340.897228                4.103581               84.0   
123          17.727040                0.939261               43.0   
124         430.187347                4.514342                5.0   
125         468.020212                4.603817                5.0   

     0_Average power  0_Centroid  0_ECDF Percentile Count_0  \
0          85.795509    2.502542                      100.0   
1           6.566842    2.477941                      100.0   
2          95.917270    2.494835                      100.0   
3          95.591698    2.505107                      100.0   
4         106.305902    2.498989                      100.0   
..               ...         ...                        ...   
121        99.747317    2.472182                      100.0   
122        68.316078    2.297769                      100.0   
123         3.552513    2.506691                      100.0   
124        86.209889    2.457373                      100.0   
125        93.791626    2.455467                      100.0   

     0_ECDF Percentile Count_1  0_ECDF Percentile_0  0_ECDF Percentile_1  \
0                        400.0             0.737727             1.086936   
1                        400.0             0.249165             0.262091   
2                        400.0             0.975656             0.980947   
3                        400.0             0.762545             1.075617   
4                        400.0             0.770530             1.234635   
..                         ...                  ...                  ...   
121                      400.0             0.784800             1.202131   
122                      400.0             0.776342             0.926267   
123                      400.0             0.183463             0.192260   
124                      400.0             0.732451             1.062091   
125                      400.0             0.646158             1.188348   

     0_ECDF_0  ...  2_Wavelet variance_0  2_Wavelet variance_1  \
0       0.002  ...              0.003322              0.019687   
1       0.002  ...              0.000828              0.002949   
2       0.002  ...              0.000127              0.000487   
3       0.002  ...              0.002664              0.013335   
4       0.002  ...              0.002535              0.015177   
..        ...  ...                   ...                   ...   
121     0.002  ...              0.009342              0.034796   
122     0.002  ...              0.000305              0.001307   
123     0.002  ...              0.001052              0.003667   
124     0.002  ...              0.004605              0.020702   
125     0.002  ...              0.002757              0.021342   

     2_Wavelet variance_2  2_Wavelet variance_3  2_Wavelet variance_4  \
0                0.049441              0.092600              0.146952   
1                0.006456              0.011349              0.017532   
2                0.001049              0.001795              0.002722   
3                0.032745              0.056265              0.077145   
4                0.040367              0.069588              0.099245   
..                    ...                   ...                   ...   
121              0.057884              0.100034              0.153607   
122              0.003269              0.006416              0.010984   
123              0.007924              0.013976         

In [80]:
df[df['Label']==1]

accx      accy      accz  Label
0     0.988581  0.196507  0.180045      1
1     0.985708  0.198905  0.192556      1
2     0.979526  0.204315  0.204461      1
3     0.980467  0.204519  0.204332      1
4     0.984234  0.204112  0.201085      1
...        ...       ...       ...    ...
3003  0.983336  0.147791  0.221924      1
3004  0.976038  0.141747  0.220276      1
3005  0.972944  0.137397  0.221315      1
3006  0.971183  0.135625  0.231532      1
3007  0.970699  0.137976  0.245045      1

[82304 rows x 4 columns]

In [81]:


base_path = "/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/Combined/Test"

# Initialize an empty DataFrame
df_test = pd.DataFrame()

for files in os.listdir(base_path):
    full_path = os.path.join(base_path, files)
    if os.path.isdir(full_path):  # Ensure `files` is a directory
        for dfs in os.listdir(full_path):
            dfs_full_path = os.path.join(full_path, dfs)
            if os.path.isfile(dfs_full_path):  # Ensure `dfs` is a file
                df1 = pd.read_csv(dfs_full_path)
                df1["Label"] = np.array([dict1[files]] * df1.shape[0])
                df_test = pd.concat([df_test, df1], axis=0)

# Now `df` contains the combined DataFrame


In [82]:
df_test[df_test['Label']==1]

accx      accy      accz  Label
0     0.951905  0.133459  0.324955      1
1     0.954166  0.140860  0.326493      1
2     0.958054  0.144883  0.328487      1
3     0.955355  0.155393  0.326331      1
4     0.950674  0.164610  0.326728      1
...        ...       ...       ...    ...
3259  1.017505  0.024498 -0.039603      1
3260  1.019046  0.025779 -0.049137      1
3261  1.028794  0.014717 -0.066147      1
3262  1.031831  0.015192 -0.069162      1
3263  1.027248  0.017098 -0.065781      1

[31424 rows x 4 columns]

In [17]:
X_train_tsfel

0_Absolute energy  0_Area under the curve  0_Autocorrelation  \
0           428.119592                4.504459                5.0   
1            32.768542                1.276929               26.0   
2           478.627177                4.882182                5.0   
3           477.002571                4.747669                5.0   
4           530.466450                5.002581                6.0   
..                 ...                     ...                ...   
121         497.739114                4.877595                3.0   
122         340.897228                4.103581               84.0   
123          17.727040                0.939261               43.0   
124         430.187347                4.514342                5.0   
125         468.020212                4.603817                5.0   

     0_Average power  0_Centroid  0_ECDF Percentile Count_0  \
0          85.795509    2.502542                      100.0   
1           6.566842    2.477941                      100.0   
2          95.917270    2.494835                      100.0   
3          95.591698    2.505107                      100.0   
4         106.305902    2.498989                      100.0   
..               ...         ...                        ...   
121        99.747317    2.472182                      100.0   
122        68.316078    2.297769                      100.0   
123         3.552513    2.506691                      100.0   
124        86.209889    2.457373                      100.0   
125        93.791626    2.455467                      100.0   

     0_ECDF Percentile Count_1  0_ECDF Percentile_0  0_ECDF Percentile_1  \
0                        400.0             0.737727             1.086936   
1                        400.0             0.249165             0.262091   
2                        400.0             0.975656             0.980947   
3                        400.0             0.762545             1.075617   
4                        400.0             0.770530             1.234635   
..                         ...                  ...                  ...   
121                      400.0             0.784800             1.202131   
122                      400.0             0.776342             0.926267   
123                      400.0             0.183463             0.192260   
124                      400.0             0.732451             1.062091   
125                      400.0             0.646158             1.188348   

     0_ECDF_0  ...  2_Wavelet variance_0  2_Wavelet variance_1  \
0       0.002  ...              0.003322              0.019687   
1       0.002  ...              0.000828              0.002949   
2       0.002  ...              0.000127              0.000487   
3       0.002  ...              0.002664              0.013335   
4       0.002  ...              0.002535              0.015177   
..        ...  ...                   ...                   ...   
121     0.002  ...              0.009342              0.034796   
122     0.002  ...              0.000305              0.001307   
123     0.002  ...              0.001052              0.003667   
124     0.002  ...              0.004605              0.020702   
125     0.002  ...              0.002757              0.021342   

     2_Wavelet variance_2  2_Wavelet variance_3  2_Wavelet variance_4  \
0                0.049441              0.092600              0.146952   
1                0.006456              0.011349              0.017532   
2                0.001049              0.001795              0.002722   
3                0.032745              0.056265              0.077145   
4                0.040367              0.069588              0.099245   
..                    ...                   ...                   ...   
121              0.057884              0.100034              0.153607   
122              0.003269              0.006416              0.010984   
123              0.007924              0.013976         

In [19]:
y_train_tsfel

2.000000000000000000e+00
0                         6.0
1                         5.0
2                         2.0
3                         2.0
4                         2.0
..                        ...
120                       1.0
121                       4.0
122                       6.0
123                       2.0
124                       2.0

[125 rows x 1 columns]

In [12]:
dt = DecisionTreeClassifier(criterion="gini", random_state=42,
        splitter="best",
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        min_weight_fraction_leaf=0.0,
        max_features=None,
        max_leaf_nodes=None,
        min_impurity_decrease=0.0,
        class_weight=None,
        ccp_alpha=0.0,
        monotonic_cst=None)

In [ ]:
dt.fit(X_train_tsfel[1:126], y_train_tsfel)

In [25]:
predictions = dt.predict(X_test_tsfel[1:25])

In [86]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [87]:
accuracy = accuracy_score(predictions, y_test_tsfel)
print(f"Accuracy: {accuracy}")

Accuracy: 0.21739130434782608


In [88]:
precision = precision_score(predictions, y_test_tsfel,average="weighted")
print(f"Precision: {precision}")

Precision: 0.8369565217391305


In [89]:
recall = recall_score(predictions, y_test_tsfel,average="weighted")
print(f"Recall: {recall}")

Recall: 0.21739130434782608


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [90]:
from sklearn.metrics import confusion_matrix

mat = confusion_matrix(predictions, y_test_tsfel)
print(f"Confusion Matrix:\n{mat}")


Confusion Matrix:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [2 1 0 0 0 0]
 [2 3 3 3 4 4]]


Question 2


From the above observations we can infer that the decision tree doesnt perform well when the depth of the tree is less than 3 and has a drastic shoot in accuracy after a depth of 3. We also observe that the model performs better with more features as compared to the raw accelerometer data where there are only 3 features.

In [24]:
X_train_final, X_test_final, y_train_final, y_test_final = train_test_split(X_test_tsfel.iloc[1:,:], y_test_tsfel, test_size=0.3, random_state=42)

In [26]:
dt.fit(X_train_final, y_train_final)

DecisionTreeClassifier(random_state=42)

In [27]:
predictions = dt.predict(X_test_final)

In [28]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [29]:
accuracy = accuracy_score(predictions, y_test_final)
print(f"Accuracy: {accuracy}")

Accuracy: 0.7142857142857143
